@startuml
title identify_clusters_small

start

:Initialize cluster_indices[];
:Set i = 0;
:Set n_events = len(events[]);

while (i < n_events?)
  :Check if start condition;

  note right
  Cluster start condition:
  - ITYPE[i] == 3
  - LO_RES_PH[i] > threshold_large
  - NEXT_INTERVAL < interval_limit | NEXT_INTERVAL==SECOND_THRES_USE_LEN
  - rt_min < RISE_TIME < rt_max
  end note

  if (is cluster start?) then (yes)
    :cluster_indices.append(i);
    :i += 1;

    while (is cluster continuation?)

      note right
      Cluster continuation condition:
      - ITYPE[i] is 3 or 4
      - PREV_INTERVAL[i] < interval_limit
        or == SECOND_THRES_USE_LEN
      end note

      :cluster_indices.append(i);
      :i += 1;
    endwhile

  else (no)
    :cluster_indices.append(i);
    :i += 1;
  endif
endwhile

:return cluster_indices[];
stop
@enduml
